import type { Metadata } from "next"
import "./globals.css"
import Link from "next/link"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export const Nav = () => {
  return (
    <nav>
      <ul className="bg-gray-500 p-3 flex gap-8 justify-end text-lg font-bold">
        <li>
          <Link href={`/`}>TOP</Link>
        </li>
        <li>
          <Link href={`/categories`}>CATEGORIES</Link>
        </li>{" "}
        <li>
          <Link href={`/site-info`}>SITE INFO</Link>
        </li>
      </ul>
    </nav>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="h-screen">
        <Nav />
        {children}
      </body>
    </html>
  )
}
