services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    # ${local の ディレクトリ}:${Docker の WORKDIR}
    volumes:
      - ./backend:/backend_src/
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://hoger:hoge@db:3306/hoge_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/frontend_src
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: hoge
      MYSQL_DATABASE: hoge_db
      MYSQL_USER: hoger
      MYSQL_PASSWORD: hoge
    ports:
      - "3306:3306"

networks:
  default:
    name: fullstack_network
